// Print-window comparison PDF: same approach as pdfExportWeb.js.
// Diff highlighting renders as BOLD rather than yellow background — more
// legible in print and friendlier to monochrome printers.

const formatRM = (n) => `RM ${Number(n).toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const truncate = (s, max) => (s && s.length > max ? s.slice(0, max - 1) + '…' : s || '');
// HTML-escape user-supplied strings so plan names containing `<`, `&`, etc.
// render as text in the print window rather than breaking the page.
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

const buildHtml = (data) => {
  const { planHeaders, inputRows, itemRows, totals, highestIndex } = data;
  const today = new Date().toLocaleDateString('en-MY', { day: 'numeric', month: 'long', year: 'numeric' });

  const planCols = planHeaders.map(p => `
    <th>
      <div class="plan-name">${esc(truncate(p.name, 40))}</div>
      <div class="plan-scheme">${esc((p.schemeId || '').toUpperCase())}</div>
      <div class="plan-sub">${esc(p.subtitle || '')}</div>
    </th>`).join('');

  const inputRowsHtml = inputRows.map(row => `
    <tr class="${row.differ ? 'diff' : ''}">
      <td class="label">${esc(row.label)}</td>
      ${row.values.map(v => `<td class="${row.differ ? 'val-bold' : 'val'}">${esc(v)}</td>`).join('')}
    </tr>`).join('');

  const itemRowsHtml = itemRows.map(row => `
    <tr>
      <td class="label">${esc(row.label)}</td>
      ${row.amounts.map(a => `<td class="val">${a == null ? '—' : (typeof a === 'number' ? formatRM(a) : esc(a))}</td>`).join('')}
    </tr>`).join('');

  const totalsHtml = totals.map((t, i) => `
    <td class="total ${i === highestIndex ? 'highest' : ''}">${formatRM(t)}${i === highestIndex ? '<div class="badge">HIGHEST</div>' : ''}</td>
  `).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Scenario Comparison</title>
<style>
  @page { size: A4 landscape; margin: 12mm; }
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #222; margin: 0; padding: 12px; }
  h1 { color: #1b5e20; font-size: 18px; margin: 0 0 4px; }
  .meta { color: #666; font-size: 11px; margin-bottom: 14px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
  thead th { background: #f1f8e9; color: #1b5e20; text-align: left; padding: 8px; border-bottom: 2px solid #2e7d32; font-size: 11px; }
  thead th .plan-name { font-size: 13px; }
  thead th .plan-scheme { font-weight: 700; color: #2e7d32; font-size: 11px; }
  thead th .plan-sub { font-size: 10px; font-weight: 400; color: #777; }
  tbody td { padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px; vertical-align: top; }
  td.label { width: 25%; color: #555; }
  td.val { color: #333; }
  td.val-bold { font-weight: 700; color: #222; }
  tr.diff td.label { font-weight: 700; }
  td.total { font-weight: 800; color: #1b5e20; font-size: 14px; }
  td.total.highest { background: #c8e6c9; }
  td.total .badge { font-size: 9px; font-weight: 700; color: #1b5e20; margin-top: 2px; }
  .section-title { background: #f5f5f5; font-weight: 700; padding: 6px 8px; font-size: 11px; color: #555; }
  .footer { color: #888; font-size: 10px; margin-top: 12px; text-align: center; }
</style></head>
<body>
  <h1>Training Grant — Scenario Comparison</h1>
  <div class="meta">${today}</div>

  <table>
    <thead>
      <tr><th class="label">Field</th>${planCols}</tr>
    </thead>
    <tbody>
      <tr><td class="section-title" colspan="${planHeaders.length + 1}">Key Inputs</td></tr>
      ${inputRowsHtml || `<tr><td class="label" colspan="${planHeaders.length + 1}">No comparable inputs.</td></tr>`}
      <tr><td class="section-title" colspan="${planHeaders.length + 1}">Cost Components</td></tr>
      ${itemRowsHtml || `<tr><td class="label" colspan="${planHeaders.length + 1}">No comparable cost components.</td></tr>`}
      <tr>
        <td class="label" style="font-weight:700;">Total Maximum Claimable</td>
        ${totalsHtml}
      </tr>
    </tbody>
  </table>

  <div class="footer">Generated by Training Grant Estimator · Millennium Resource Ltd · Not affiliated with HRD Corp</div>
</body></html>`;
};

export function exportComparisonPDF(data) {
  if (!data || !Array.isArray(data.planHeaders) || data.planHeaders.length === 0) return;
  const html = buildHtml(data);
  const w = window.open('', '_blank', 'width=1000,height=800');
  if (!w) { alert('Please allow pop-ups to export PDF.'); return; }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 250);
}
